apiVersion: apps/v1
kind: Deployment
metadata:
  name: master-deployment
spec:
  replicas: 1  # You can scale the number of replicas if needed
  selector:
    matchLabels:
      app: master-kafka-consumer
  template:
    metadata:
      labels:
        app: master-kafka-consumer
    spec:
      restartPolicy: Always
      containers:
      - name: master-container
        image: master:1.0  # Replace with the name of your Docker image if it's different
        imagePullPolicy: Never
        env:
        - name: KAFKA_BROKER_SERVICE
          value: "my-kafka.kafka.svc.cluster.local:9092"  # Kafka broker service
        - name: KAFKA_CONSUMER_GROUP
          value: "master-group"  # Consumer group
        - name: KAFKA_USERNAME
          value: "user1"  # Username for Kafka
        - name: KAFKA_CONSUMER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-kafka-user-passwords
              key: client-passwords
        - name: KAFKA_AUTO_OFFSET_RESET
          value: "latest"
        - name: KAFKA_CONSUMER_TOPIC
          value: "workers_topic"
        - name: KAFKA_PRODUCER_TOPIC
          value: "master"
        # Additional environment variables as needed
      nodeSelector:
        kubernetes.io/hostname: kind-control-plane  # Control-plane label may vary based on the cluster setup
      tolerations:  # Control plane nodes often have a taint that must be tolerated by the pod
      - key: "node-role.kubernetes.io/control-plane"
        effect: "NoSchedule"
