apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: worker2-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  volumeName: worker2-pv

