apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker1-deployment
spec:
  replicas: 1  # You can scale the number of replicas if needed
  selector:
    matchLabels:
      app: worker1-kafka-producer
  template:
    metadata:
      labels:
        app: worker1-kafka-producer
    spec:
      restartPolicy: Always
      containers:
      - name: worker1-container
        image: worker1:1.0
        imagePullPolicy: Never
        env:
        - name: KAFKA_BROKER_SERVICE
          value: "my-kafka.kafka.svc.cluster.local:9092"  # Kafka broker service
        - name: KAFKA_USERNAME
          value: "user1"  # Username for Kafka
        - name: KAFKA_PASSWORD_ENCODED
          valueFrom:
            secretKeyRef:
              name: my-kafka-user-passwords
              key: client-passwords
        - name: KAFKA_CONSUMER_GROUP
          value: "worker1-group"  # Unique consumer group for worker1
        volumeMounts:
        - mountPath: "/mnt"
          name: worker1-volume
      volumes:
      - name: worker1-volume
        persistentVolumeClaim:
          claimName: worker1-pvc
      nodeSelector:
        kubernetes.io/hostname: kind-worker
